//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazKitaplikV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALTTURLER
    {
        public int Alt_TurID { get; set; }
        public Nullable<int> TurID { get; set; }
        public string Alt_Tur_Adi { get; set; }
    }
}
