//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazKitaplikV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMANETLER
    {
        public int EmanetID { get; set; }
        public Nullable<int> KitapID { get; set; }
        public string Kime_Verildi { get; set; }
        public Nullable<System.DateTime> Verilme_Tarihi { get; set; }
        public Nullable<System.DateTime> Geri_Alinma_Tarihi { get; set; }
    }
}
