//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazKitaplikV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OKUNAN_KITAPLAR
    {
        public int OkumaID { get; set; }
        public Nullable<int> KitapID { get; set; }
        public Nullable<int> Degerlendirme_Puani { get; set; }
        public string Yorum { get; set; }
        public Nullable<System.DateTime> Baslama_Tarihi { get; set; }
        public Nullable<System.DateTime> Bitirme_Tarihi { get; set; }
    }
}
