//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyazKitaplikV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YAYINLAR
    {
        public int YayinID { get; set; }
        public string Yayin_Adi { get; set; }
    }
}
